export const users = {
    '12345': {
      leadId: '280843',
      accountNumber: '12345',
      nationalId: '12345',
      clientName: 'Beatrice Florah Lundu',
      salesTerritory: '599',
      duka: 'Majengo Duka Zone',
      groupName: 'Green Farmers Group',
      currentStatus: 'Check Credit Score',
      statusComment: 'The lead is not in a group and has a group loan',
      phoneNumber: '+254712345678',
    },
    '67890': {
      leadId: '798323',
      accountNumber: '67890',
      nationalId: '67890',
      clientName: 'Chepkorir Betty',
      salesTerritory: '103',
      region: 'Lake Region',
      duka: 'Soy Duka',
      groupName: 'Bidii',
      currentStatus: 'Awaiting Delivery Planning',
      statusComment: 'Products collected at duka on 25th March',
      phoneNumber: '+254798765432',
    },
    '24680': {
      leadId: '213986',
      accountNumber: '24680',
      nationalId: '24680',
      clientName: '	Rofina Amai Ekwai',
      salesTerritory: '369',
      region: 'Western',
      duka: 'Kakamega Duka',
      groupName: 'Harvest Heroes',
      currentStatus: 'Lead is not Qualified',
      statusComment: 'Client notified, pickup scheduled for tomorrow',
      phoneNumber: '+254701112233',
    },
  };
  