export const macros = [
  {
    title: "Delivery Schedule Inquiry",
    body: `Client called to inquire when they will receive products enrolled for.\n\nLead ID:\nAccount Number:\nSales Territory:\nDuka:\nCurrent Status:\n\nComments:\n\nNotes:\n\nAdvise the clients to be patient, as they will receive an SMS informing them when to pick up their products from the duka. Verify that the phone number recorded on PaygOps is accurate to ensure they receive the communication.`,
  },
  {
    title: "Changing Offers/Add ons",
    body: `Client / TA called in to request changing of add-ons/offers\n\nClient Name:\nLead ID:\nNational ID:\nInput name:\nQuantity:\nComments:\n\nFor paygOps clients:\n- If the client requests for changing add-ons or offers, advise them to reach out to their relevant TAs for support\n- If a TA requests to change add-ons or offers, walk the TA through the steps to effect the changes. Support them to unlock the add-ons for them to effect the changes and advise them to save on their end. DO NOT change the add-ons or offers on behalf of the TAs.\n- In case the TAs report that they do not have edit permissions or have a network challenge to do the changes, advise them to raise the ITO Jira ticket to be supported.\n- You are only allowed to assist the Client/TA in either dropping the product or swapping it for one that matches the originally signed item.\n\nFor Evolution clients:\n- If clients request to change add-ons or offers, advise them to reach out to their relevant TAs for support\n- If a TA requests changes to add-ons or offers, assist them in making the adjustments. (for those who have rights). In case you do not have the rights to make the adjustments, escalate the case to the Staff queue team as Open.`,
  },
  {
    title: "Group Information Change / Addition Request",
    body: `This macro should be used to record cases of clients/TAs calling to request a change of group name details, add a client to a group, or confirm his / her group name. GL change requests should not be recorded here.\n\nClient Name:\nLead ID:\nAccount Number:\nCorrect group Name:\nWrong group Name:\nTerritory:\nComment on the status:\n\nNote:\nIf the client calls to request a change of group name or request to be added to a group, advise the client to reach out to the TA for support and Solve the case on FCR.\nIf the TA reports that the client is removed from the group, advise the TA to add the client in a qualified group and Solve the case on FCR.\nIf the TA reports that they are unable to add the client to a group, and the status is at “Awaiting Delivery Planning” with the comment: “The lead is not in a group and has a Group Loan offer”, support the TA by:\n- Unlocking the addons (to allow the TA to add the client to a qualified group) and advise the TA to make the changes.\n- After the TA is done with changes, Save the addons then, reload the page. The status will move to Awaiting Delivery Fee.\n- Refresh the page for the status to move to Awaiting Loan Approval, then, refresh to Awaiting Qualification, and the status will revert back to Awaiting Delivery Planning with no comment.`,
  },
  {
    title: "National ID Photo Validation (OCR at enrollment)",
    body: `TA/Client calls to inquire why the National ID and photo did not match or OCR Endpoint failed with Error 500\n\nAccount Number:\nLead ID:\nZone:\nCurrent Status:\n\nComment on the status:\n\nIs the front photo of the national ID visible?\n\nIf Yes, check dead space and advise the TA to crop the ID from the gallery and re-upload. The TA should focus on the ID to avoid any dead space around the ID. Solve the case on FCR.\n\nIf No, advise the TA to check the network connection and fully synchronize the tablet to the latest version then delete the initial photo, take a fresh photo, and save. \nIf the ID photo has not been synchronized, please synchronize again for verification.\nReturn the status to: ‘Interested in OAF’, ‘Check Credit score’, and then ‘Ready to Start Qualification’. This will allow the status to move to ‘Awaiting Qualification’. Solve the case on FCR.\n\nIf the TA indicates that they have taken the synchronization steps but still cannot see the uploaded photo, inform the TA to fill in the OCR escalation form and submit the case as Solved. Remember to CC the TA on the Zendesk ticket.\n\nIf it is not a synchronization issue, and the TA indicates that they have taken the steps above but still cannot validate the National ID, document the case and escalate the Zendesk ticket to Digital Channels as Open.`,
  },
  {
    title: "Over-payment Transfer Request",
    body: `The client called to request for an overpayment transfer of Ksh (        )\n\nLead ID:\nClient Name:\nNational ID:\nRoster Account / PaygOps Contract No:\nAmount:\nComments:\nNature of transfer: Core to Core / Core to PaygOps / PaygOps to PaygOps\n\nNote:\n- The overpayment transfer request will only be successful if the lead’s status is past ‘Awaiting Qualification’.\n- Ensure that the client's name and NID are the same on both Roster and PaygOps before requesting for the overpayment transfer.\n- An overpayment transfer request can only be made to the client's own account and not to any other.\n- Inform the client that an overpayment transfer request is processed within 7 working days.\n\nIf the transfer has not been done, send the case to leakey.omondi@oneacrefund.org as OPEN.`,
  },
  {
    title: "Balance Inquiry",
    body: `Farmer called to ask about his/her balance which was:\n\nAccount Number:\nLead ID:\nNational ID:\nComment:\n\nTake them through how to check the account balance:\n\nDial *689#\nKey in your 8-digit Account Number\nSelect option 2\nYour balance for the season will show on the screen of your phone.`,
  },
  {
    title: "Client Registration",
    body: `A client calls in to enroll in Tupande. Ask the client for the following details:\n\nClient Name:\nCounty:\nSub County:\nWard:\nPaygOps Client Lead ID:\nComments:\n\nNote:\n- Do not register/add the client on PaygOps.\n- Use the Duka Locator to identify the duka nearest to the client and advise the client to visit the duka for registration. Solve the case on FCR.\n- For returning clients, refer them to the TA and Solve the case on FCR.\n- If the client is not in the Tupande region, apologize to them, inform them that we are not present in their area, and Solve the case on FCR.\n- For cases where clients claim they visited a duka but were not assisted, or where TAs claim to have paused enrollment, send the case to the Follow-up team as Open.\n\nThe Follow-up team will reach out to the duka staff, TA, and RMs to understand the challenge and assist the client.`,
  },
  {
    title: "IPRS Validation Issue",
    body: `TA/Client called to inquire about stalled status despite correct National ID details.\n\nClient Name:\nAccount Number:\nCurrent Status:\nComment on the status:\n\nNote: Check if National ID number and Names on Paygops match the uploaded National ID image.\n- If they match but comment still says "NID not verified", return status to "Interested in OAF" > "Check Credit Score" > "Ready to start Qualification", then refresh. If issue persists, escalate to Digital Channels as Open.\n- If they don’t match, advise TA to edit client info to match the ID and Solve on FCR.\n- If comment is “Future contract value is greater than the credit maximum”, advise client/TA to reduce addons and Solve on FCR.\n- If there’s no comment, check the National ID Verification and Credit Score Results form under “iprsCheck” section, then escalate to Digital Channels as Open.`
  },  
  {
    title: "Lead is not Qualified",
    body: `Lead ID:\nAccount:\nCurrent Status:\n\nComments:\n\nNotes:\n- This macro is used to document cases where the lead is stuck at “Lead is Not Qualified” status.\n- Return the status to: Interested in OAF > Check Credit Score > Ready to start Qualification. The status will move to Awaiting Delivery Fee.\n- Wait a few seconds and refresh the page. The lead will move to the next status.\n- Share the new status and Solve the case on FCR.\n\nIf the status reverts back to "Lead is Not Qualified":\n- Check both PaygOps and Roster to see if the client has any pending loans.\n\nIf **there are outstanding loans**, advise the client to complete repayment before enrolling again. Solve the case on FCR.\n\nIf **no outstanding loans**, escalate the case to joseph.nyamohanga@oneacrefund.org as Open.\nInform the client the issue will be handled within 3 working days.`,
  },
  {
    title: "Payment Transfer Request",
    body: `Client called to request a payment transfer of Ksh (     )\n\nMpesa Code:\nClient Name:\nLead ID:\nNational ID:\nRepayment Date:\nPayment Phone Number:\nPayment Amount:\nWrong account paid to:\nCorrect account to be credited:\nMode of payment:\n\nComments:\n\nNote:\nIf transfer is between different clients, inform the client it will be done within 2 working days and assign to Kevin Juma as Open.\nIf between same client, use the Over-payment Transfer Request macro.\nReception agent should validate the transaction, attach a screenshot of the Buy Goods statement, and assign the case.\nDo not transfer funds without consent from the client who received the payment.\nFor transfers from completed contracts, submit two separate transfer requests.`
  },  
  {
    title: "Solar Product Activation Codes",
    body: `Client called to request activation codes for their solar product.\n\nAccount Number:\nLead ID:\nLamp Type:\nSerial Number:\nDuka of Purchase:\nYear of Issue:\nPhone Number to Be Reached:\n\nComments:\n\nMandatory: Kindly update the following Zendesk Fields: Caller's Phone Number, Year of Issue, Serial Number, National ID, Lead ID.\n\nSteps to Follow:\n1. Ask for the Serial Number of the product.\n2. Search for the activation code on the Duka Warranty - Activation Codes tracker (Solar Activation Codes tab).\n3. If found, read the code to the client.\n4. If client prefers SMS, fill out the Call Reception SMS Form and indicate preference.\n5. If lamp does not accept the code, advise client to submit it to nearest Duka.\n6. If code shows 'invalid', advise client to visit the nearest Duka.\n7. If serial number is on tracker but code is missing, assign ticket to leakey.omondi@oneacrefund.org as OPEN.\n8. If serial number is not found, direct client to Duka of Purchase for DA support.\n\nFor staff-related cases: Staff should call HR Hotline (0800 720 958) and press 2 for 2022 lamp codes. Use Kenya Staff Unlock Codes for 2023 tracker for LR2023 lamps.\n\nNote: Duka Warranty - Activation Codes tracker is automated to generate codes instantly for DA activation at the Duka.`
  },  
  {
    title: "Payment Tracking",
    body: `Client called to follow up on a payment they made.\n\nPayment Method:\nDate:\nAmount:\nReference:\n\nChecked payment logs and confirmed status with client.`,
  },
  {
    title: "Product Warranty or Faulty Item Report",
    body: `A client called to report that their product is faulty or that a solar product is displaying error 200, 400, or 500. The client may also request assistance with settings (e.g., language or time).\n\nMode of Payment: (Roster, Cash (Duka), PaygOps, Fineract - Coast clients)\nProduct Serial Number or Phone IMEI:\nYear the Item was Received:\nProduct Type (Lamp/Phone/Cookstove):\nAccount Number:\nClient Phone Number:\nHas this Item Been Replaced Before?:\nNature of the Problem:\nHas the Item Been Dropped at the Duka?:\nDuka Name Where the Product Was Submitted:\nDate of Submission at the Duka:\nDate TA Collected the Product:\n\nComment:\n\nNotes:\n\nIf the product has **not been submitted** at the Duka:\n- Request the client to bring the product to the Duka or submit it to their TA so that it can be assessed and possibly sent for warranty processing.\n\nIf the product was **submitted for warranty processing**:\n- Check the **Tupande Warranty Dashboard** (Column AW) to track product warranty movement.\n- For cases reported **before Feb 2023**, check the **Archived Tupande Warranty Dashboard**.\n\nTo clear all **fault errors** on Biolite Home Systems:\n1. Long press buttons 1 and 5 simultaneously without releasing, or\n2. Long press button 1, then button 5 while releasing until the error clears.\n3. Stop pressing once the error clears (note: the lamp will not go off).\n✅ If Fault 400 clears, **Solve the case on FCR**.\n❌ If it does **not clear**, advise the client to return the lamp to the Duka or submit it to the TA for further diagnosis.\n\nFor **language or time setting issues** on BHS:\n- Refer to the official training material on BHS settings.\n\nWarranty Duration Guide:\n🟢 **2-Year Warranty**: Biolite Home System, SK Boom, SK Charge, SK Pico, SK Pro 300, SK Pro II, Sunking Home, Dlight T200R, Envirofit Cookstoves, Biolite Charcoal Cookstoves\n🟡 **1-Year Warranty**: Tecno Phones\n🔴 **2-Week Warranty**: Knapsack Sprayer Pumps, Wheelbarrow Parts, Harvest Drying Sheets\n\n📌 For corner cases: Assign **benjamin.juma@oneacrefund.org** as **Open**.\n\n🔍 Refer to:\n- Warranty Guide\n- CC Warranty Guide\n- Solar Product FAQs`,
  },  
  {
    title: "Phone Number Change",
    body: `This macro should be used to record requests to change phone numbers.\n\nLead ID:\nAccount:\nSales Territory:\nCurrent Phone Number:\nNew Phone Number:\n\nRetain Previous Number? (Yes/No):\nReason for Changing:\n\nComments: Fill out this form and submit it before changing the phone number on PaygOps.\n\nNotes:\n- Phone number changes will only be processed upon direct request from the farmer to the CC team for both Leads and Clients.\n- TAs, DAs, Zs or any Tupande staff are NOT authorized to request phone number changes on behalf of farmers.\n\nBefore making any change:\n1. Verify the client's identity by asking these 3 security questions:\n   - National ID Number\n   - Date of Birth (as per NID)\n   - Last payment made to the client's account\n\n2. After verification, collect both the Current and New phone numbers.\n3. For **Leads**, make the change directly on call.\n4. Confirm the number change to the client and read back the new number.\n5. Resend OTP under the 'Phone Number Validation' tab by checking the 'Resend OTP Code' box, then advise the client to share the OTP with the TA for validation.\n6. Solve the case on FCR.\n\nFor **returning clients or completed accounts**:\n- Escalate the case to **Annet Nyakundi** or **Evans Maramai** as **Open** for support.\n\nIf the client is **following up on a failed refund due to incorrect phone number**:\n- If the status is NOT complete (i.e. still a Lead), fill and submit the form, change the number on PaygOps, and record it in the tracker (Column M) and mark YES in Column N.\n- If the number **cannot be changed** or the status is **Complete**, escalate to **Annet Nyakundi** or **Evans Maramai** as **Open**.\n\nRefer to the official guide for more details on how to make changes on PaygOps.`,
  },  
  {
    title: "Funeral Insurance",
    body: `Client called to inquire about their funeral insurance policy.\n\nClient Name:\nPolicy Number (if any):\nLead ID:\n\nProvided policy status and next steps.`,
  },
];
